[package]
name = "func_types"
version = "0.1.0"
authors = ["Damien Pontifex <damien.pontifex@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "*", features = ["serde"] }
serde = "*"
serde_json = "*"
uuid = { version = "*", features = ["serde", "v4"] }
